# Database Configuration (TiDB Cloud)
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/grossery_db?enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=rRMV7JDk7xhYi9z.root
spring.datasource.password=Pc45HT9UFaAiJgG2
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
# Use 'update' for development. When running strictly in production later, you might want to switch to 'validate' or 'none' after the schema is stable.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Server
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG

# Mailtrap SMTP Settings
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d48c5773377d18
spring.mail.password=097da1f35b7fd3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
